stages:
  clean_data:
    cmd: python src/scripts/data/clean_data.py
    deps:
      - src/scripts/data/clean_data.py
      - data/raw/reddit_data.csv
    outs:
      - data/interim/reddit_data.csv

  make_datasets:
    cmd: python src/scripts/data/make_datasets.py
    deps:
      - src/scripts/data/make_datasets.py
      - data/interim/reddit_data.csv
    outs:
      - data/processed/reddit_performance/X_train.csv
      - data/processed/reddit_performance/X_test.csv
      - data/processed/reddit_training_style/X_train.csv
      - data/processed/reddit_training_style/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train_performance_model:
    cmd: python src/scripts/models/train_performance_model.py
    deps:
      - src/scripts/models/train_performance_model.py
      - data/processed/reddit_performance/X_train.csv
      - data/processed/reddit_performance/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - data/models/performance_model/model.pkl
      #- data/models/performance_model/shap_summary_plot.png
